#include "color.hpp"
#include <iostream>

void exhaustive_hue_api_test()
{
    std::cout << hue::black << "hue::black" << hue::reset << std::endl;
    std::cout << hue::blue << "hue::blue" << hue::reset << std::endl;
    std::cout << hue::green << "hue::green" << hue::reset << std::endl;
    std::cout << hue::aqua << "hue::aqua" << hue::reset << std::endl;
    std::cout << hue::cyan << "hue::cyan" << hue::reset << std::endl;
    std::cout << hue::red << "hue::red" << hue::reset << std::endl;
    std::cout << hue::purple << "hue::purple" << hue::reset << std::endl;
    std::cout << hue::magenta << "hue::magenta" << hue::reset << std::endl;
    std::cout << hue::yellow << "hue::yellow" << hue::reset << std::endl;
    std::cout << hue::white << "hue::white" << hue::reset << std::endl;
    std::cout << hue::gray << "hue::gray" << hue::reset << std::endl;
    std::cout << hue::light_blue << "hue::light_blue" << hue::reset << std::endl;
    std::cout << hue::light_green << "hue::light_green" << hue::reset << std::endl;
    std::cout << hue::light_aqua << "hue::light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_cyan << "hue::light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_red << "hue::light_red" << hue::reset << std::endl;
    std::cout << hue::light_purple << "hue::light_purple" << hue::reset << std::endl;
    std::cout << hue::light_magenta << "hue::light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_yellow << "hue::light_yellow" << hue::reset << std::endl;
    std::cout << hue::bright_white << "hue::bright_white" << hue::reset << std::endl;
    std::cout << hue::on_black << "hue::on_black" << hue::reset << std::endl;
    std::cout << hue::on_blue << "hue::on_blue" << hue::reset << std::endl;
    std::cout << hue::on_green << "hue::on_green" << hue::reset << std::endl;
    std::cout << hue::on_aqua << "hue::on_aqua" << hue::reset << std::endl;
    std::cout << hue::on_cyan << "hue::on_cyan" << hue::reset << std::endl;
    std::cout << hue::on_red << "hue::on_red" << hue::reset << std::endl;
    std::cout << hue::on_purple << "hue::on_purple" << hue::reset << std::endl;
    std::cout << hue::on_magenta << "hue::on_magenta" << hue::reset << std::endl;
    std::cout << hue::on_yellow << "hue::on_yellow" << hue::reset << std::endl;
    std::cout << hue::on_white << "hue::on_white" << hue::reset << std::endl;
    std::cout << hue::on_gray << "hue::on_gray" << hue::reset << std::endl;
    std::cout << hue::on_light_blue << "hue::on_light_blue" << hue::reset << std::endl;
    std::cout << hue::on_light_green << "hue::on_light_green" << hue::reset << std::endl;
    std::cout << hue::on_light_aqua << "hue::on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::on_light_cyan << "hue::on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::on_light_red << "hue::on_light_red" << hue::reset << std::endl;
    std::cout << hue::on_light_purple << "hue::on_light_purple" << hue::reset << std::endl;
    std::cout << hue::on_light_magenta << "hue::on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::on_light_yellow << "hue::on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::on_bright_white << "hue::on_bright_white" << hue::reset << std::endl;
    std::cout << hue::black_on_black << "hue::black_on_black" << hue::reset << std::endl;
    std::cout << hue::black_on_blue << "hue::black_on_blue" << hue::reset << std::endl;
    std::cout << hue::black_on_green << "hue::black_on_green" << hue::reset << std::endl;
    std::cout << hue::black_on_aqua << "hue::black_on_aqua" << hue::reset << std::endl;
    std::cout << hue::black_on_cyan << "hue::black_on_cyan" << hue::reset << std::endl;
    std::cout << hue::black_on_red << "hue::black_on_red" << hue::reset << std::endl;
    std::cout << hue::black_on_purple << "hue::black_on_purple" << hue::reset << std::endl;
    std::cout << hue::black_on_magenta << "hue::black_on_magenta" << hue::reset << std::endl;
    std::cout << hue::black_on_yellow << "hue::black_on_yellow" << hue::reset << std::endl;
    std::cout << hue::black_on_white << "hue::black_on_white" << hue::reset << std::endl;
    std::cout << hue::black_on_gray << "hue::black_on_gray" << hue::reset << std::endl;
    std::cout << hue::black_on_light_blue << "hue::black_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::black_on_light_green << "hue::black_on_light_green" << hue::reset << std::endl;
    std::cout << hue::black_on_light_aqua << "hue::black_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::black_on_light_cyan << "hue::black_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::black_on_light_red << "hue::black_on_light_red" << hue::reset << std::endl;
    std::cout << hue::black_on_light_purple << "hue::black_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::black_on_light_magenta << "hue::black_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::black_on_light_yellow << "hue::black_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::black_on_bright_white << "hue::black_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::blue_on_black << "hue::blue_on_black" << hue::reset << std::endl;
    std::cout << hue::blue_on_blue << "hue::blue_on_blue" << hue::reset << std::endl;
    std::cout << hue::blue_on_green << "hue::blue_on_green" << hue::reset << std::endl;
    std::cout << hue::blue_on_aqua << "hue::blue_on_aqua" << hue::reset << std::endl;
    std::cout << hue::blue_on_cyan << "hue::blue_on_cyan" << hue::reset << std::endl;
    std::cout << hue::blue_on_red << "hue::blue_on_red" << hue::reset << std::endl;
    std::cout << hue::blue_on_purple << "hue::blue_on_purple" << hue::reset << std::endl;
    std::cout << hue::blue_on_magenta << "hue::blue_on_magenta" << hue::reset << std::endl;
    std::cout << hue::blue_on_yellow << "hue::blue_on_yellow" << hue::reset << std::endl;
    std::cout << hue::blue_on_white << "hue::blue_on_white" << hue::reset << std::endl;
    std::cout << hue::blue_on_gray << "hue::blue_on_gray" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_blue << "hue::blue_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_green << "hue::blue_on_light_green" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_aqua << "hue::blue_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_cyan << "hue::blue_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_red << "hue::blue_on_light_red" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_purple << "hue::blue_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_magenta << "hue::blue_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::blue_on_light_yellow << "hue::blue_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::blue_on_bright_white << "hue::blue_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::green_on_black << "hue::green_on_black" << hue::reset << std::endl;
    std::cout << hue::green_on_blue << "hue::green_on_blue" << hue::reset << std::endl;
    std::cout << hue::green_on_green << "hue::green_on_green" << hue::reset << std::endl;
    std::cout << hue::green_on_aqua << "hue::green_on_aqua" << hue::reset << std::endl;
    std::cout << hue::green_on_cyan << "hue::green_on_cyan" << hue::reset << std::endl;
    std::cout << hue::green_on_red << "hue::green_on_red" << hue::reset << std::endl;
    std::cout << hue::green_on_purple << "hue::green_on_purple" << hue::reset << std::endl;
    std::cout << hue::green_on_magenta << "hue::green_on_magenta" << hue::reset << std::endl;
    std::cout << hue::green_on_yellow << "hue::green_on_yellow" << hue::reset << std::endl;
    std::cout << hue::green_on_white << "hue::green_on_white" << hue::reset << std::endl;
    std::cout << hue::green_on_gray << "hue::green_on_gray" << hue::reset << std::endl;
    std::cout << hue::green_on_light_blue << "hue::green_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::green_on_light_green << "hue::green_on_light_green" << hue::reset << std::endl;
    std::cout << hue::green_on_light_aqua << "hue::green_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::green_on_light_cyan << "hue::green_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::green_on_light_red << "hue::green_on_light_red" << hue::reset << std::endl;
    std::cout << hue::green_on_light_purple << "hue::green_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::green_on_light_magenta << "hue::green_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::green_on_light_yellow << "hue::green_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::green_on_bright_white << "hue::green_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::aqua_on_black << "hue::aqua_on_black" << hue::reset << std::endl;
    std::cout << hue::aqua_on_blue << "hue::aqua_on_blue" << hue::reset << std::endl;
    std::cout << hue::aqua_on_green << "hue::aqua_on_green" << hue::reset << std::endl;
    std::cout << hue::aqua_on_aqua << "hue::aqua_on_aqua" << hue::reset << std::endl;
    std::cout << hue::aqua_on_cyan << "hue::aqua_on_cyan" << hue::reset << std::endl;
    std::cout << hue::aqua_on_red << "hue::aqua_on_red" << hue::reset << std::endl;
    std::cout << hue::aqua_on_purple << "hue::aqua_on_purple" << hue::reset << std::endl;
    std::cout << hue::aqua_on_magenta << "hue::aqua_on_magenta" << hue::reset << std::endl;
    std::cout << hue::aqua_on_yellow << "hue::aqua_on_yellow" << hue::reset << std::endl;
    std::cout << hue::aqua_on_white << "hue::aqua_on_white" << hue::reset << std::endl;
    std::cout << hue::aqua_on_gray << "hue::aqua_on_gray" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_blue << "hue::aqua_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_green << "hue::aqua_on_light_green" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_aqua << "hue::aqua_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_cyan << "hue::aqua_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_red << "hue::aqua_on_light_red" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_purple << "hue::aqua_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_magenta << "hue::aqua_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::aqua_on_light_yellow << "hue::aqua_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::aqua_on_bright_white << "hue::aqua_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::cyan_on_black << "hue::cyan_on_black" << hue::reset << std::endl;
    std::cout << hue::cyan_on_blue << "hue::cyan_on_blue" << hue::reset << std::endl;
    std::cout << hue::cyan_on_green << "hue::cyan_on_green" << hue::reset << std::endl;
    std::cout << hue::cyan_on_aqua << "hue::cyan_on_aqua" << hue::reset << std::endl;
    std::cout << hue::cyan_on_cyan << "hue::cyan_on_cyan" << hue::reset << std::endl;
    std::cout << hue::cyan_on_red << "hue::cyan_on_red" << hue::reset << std::endl;
    std::cout << hue::cyan_on_purple << "hue::cyan_on_purple" << hue::reset << std::endl;
    std::cout << hue::cyan_on_magenta << "hue::cyan_on_magenta" << hue::reset << std::endl;
    std::cout << hue::cyan_on_yellow << "hue::cyan_on_yellow" << hue::reset << std::endl;
    std::cout << hue::cyan_on_white << "hue::cyan_on_white" << hue::reset << std::endl;
    std::cout << hue::cyan_on_gray << "hue::cyan_on_gray" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_blue << "hue::cyan_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_green << "hue::cyan_on_light_green" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_aqua << "hue::cyan_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_cyan << "hue::cyan_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_red << "hue::cyan_on_light_red" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_purple << "hue::cyan_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_magenta << "hue::cyan_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::cyan_on_light_yellow << "hue::cyan_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::cyan_on_bright_white << "hue::cyan_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::red_on_black << "hue::red_on_black" << hue::reset << std::endl;
    std::cout << hue::red_on_blue << "hue::red_on_blue" << hue::reset << std::endl;
    std::cout << hue::red_on_green << "hue::red_on_green" << hue::reset << std::endl;
    std::cout << hue::red_on_aqua << "hue::red_on_aqua" << hue::reset << std::endl;
    std::cout << hue::red_on_cyan << "hue::red_on_cyan" << hue::reset << std::endl;
    std::cout << hue::red_on_red << "hue::red_on_red" << hue::reset << std::endl;
    std::cout << hue::red_on_purple << "hue::red_on_purple" << hue::reset << std::endl;
    std::cout << hue::red_on_magenta << "hue::red_on_magenta" << hue::reset << std::endl;
    std::cout << hue::red_on_yellow << "hue::red_on_yellow" << hue::reset << std::endl;
    std::cout << hue::red_on_white << "hue::red_on_white" << hue::reset << std::endl;
    std::cout << hue::red_on_gray << "hue::red_on_gray" << hue::reset << std::endl;
    std::cout << hue::red_on_light_blue << "hue::red_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::red_on_light_green << "hue::red_on_light_green" << hue::reset << std::endl;
    std::cout << hue::red_on_light_aqua << "hue::red_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::red_on_light_cyan << "hue::red_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::red_on_light_red << "hue::red_on_light_red" << hue::reset << std::endl;
    std::cout << hue::red_on_light_purple << "hue::red_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::red_on_light_magenta << "hue::red_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::red_on_light_yellow << "hue::red_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::red_on_bright_white << "hue::red_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::purple_on_black << "hue::purple_on_black" << hue::reset << std::endl;
    std::cout << hue::purple_on_blue << "hue::purple_on_blue" << hue::reset << std::endl;
    std::cout << hue::purple_on_green << "hue::purple_on_green" << hue::reset << std::endl;
    std::cout << hue::purple_on_aqua << "hue::purple_on_aqua" << hue::reset << std::endl;
    std::cout << hue::purple_on_cyan << "hue::purple_on_cyan" << hue::reset << std::endl;
    std::cout << hue::purple_on_red << "hue::purple_on_red" << hue::reset << std::endl;
    std::cout << hue::purple_on_purple << "hue::purple_on_purple" << hue::reset << std::endl;
    std::cout << hue::purple_on_magenta << "hue::purple_on_magenta" << hue::reset << std::endl;
    std::cout << hue::purple_on_yellow << "hue::purple_on_yellow" << hue::reset << std::endl;
    std::cout << hue::purple_on_white << "hue::purple_on_white" << hue::reset << std::endl;
    std::cout << hue::purple_on_gray << "hue::purple_on_gray" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_blue << "hue::purple_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_green << "hue::purple_on_light_green" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_aqua << "hue::purple_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_cyan << "hue::purple_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_red << "hue::purple_on_light_red" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_purple << "hue::purple_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_magenta << "hue::purple_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::purple_on_light_yellow << "hue::purple_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::purple_on_bright_white << "hue::purple_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::magenta_on_black << "hue::magenta_on_black" << hue::reset << std::endl;
    std::cout << hue::magenta_on_blue << "hue::magenta_on_blue" << hue::reset << std::endl;
    std::cout << hue::magenta_on_green << "hue::magenta_on_green" << hue::reset << std::endl;
    std::cout << hue::magenta_on_aqua << "hue::magenta_on_aqua" << hue::reset << std::endl;
    std::cout << hue::magenta_on_cyan << "hue::magenta_on_cyan" << hue::reset << std::endl;
    std::cout << hue::magenta_on_red << "hue::magenta_on_red" << hue::reset << std::endl;
    std::cout << hue::magenta_on_purple << "hue::magenta_on_purple" << hue::reset << std::endl;
    std::cout << hue::magenta_on_magenta << "hue::magenta_on_magenta" << hue::reset << std::endl;
    std::cout << hue::magenta_on_yellow << "hue::magenta_on_yellow" << hue::reset << std::endl;
    std::cout << hue::magenta_on_white << "hue::magenta_on_white" << hue::reset << std::endl;
    std::cout << hue::magenta_on_gray << "hue::magenta_on_gray" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_blue << "hue::magenta_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_green << "hue::magenta_on_light_green" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_aqua << "hue::magenta_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_cyan << "hue::magenta_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_red << "hue::magenta_on_light_red" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_purple << "hue::magenta_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_magenta << "hue::magenta_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::magenta_on_light_yellow << "hue::magenta_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::magenta_on_bright_white << "hue::magenta_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::yellow_on_black << "hue::yellow_on_black" << hue::reset << std::endl;
    std::cout << hue::yellow_on_blue << "hue::yellow_on_blue" << hue::reset << std::endl;
    std::cout << hue::yellow_on_green << "hue::yellow_on_green" << hue::reset << std::endl;
    std::cout << hue::yellow_on_aqua << "hue::yellow_on_aqua" << hue::reset << std::endl;
    std::cout << hue::yellow_on_cyan << "hue::yellow_on_cyan" << hue::reset << std::endl;
    std::cout << hue::yellow_on_red << "hue::yellow_on_red" << hue::reset << std::endl;
    std::cout << hue::yellow_on_purple << "hue::yellow_on_purple" << hue::reset << std::endl;
    std::cout << hue::yellow_on_magenta << "hue::yellow_on_magenta" << hue::reset << std::endl;
    std::cout << hue::yellow_on_yellow << "hue::yellow_on_yellow" << hue::reset << std::endl;
    std::cout << hue::yellow_on_white << "hue::yellow_on_white" << hue::reset << std::endl;
    std::cout << hue::yellow_on_gray << "hue::yellow_on_gray" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_blue << "hue::yellow_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_green << "hue::yellow_on_light_green" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_aqua << "hue::yellow_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_cyan << "hue::yellow_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_red << "hue::yellow_on_light_red" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_purple << "hue::yellow_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_magenta << "hue::yellow_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::yellow_on_light_yellow << "hue::yellow_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::yellow_on_bright_white << "hue::yellow_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::white_on_black << "hue::white_on_black" << hue::reset << std::endl;
    std::cout << hue::white_on_blue << "hue::white_on_blue" << hue::reset << std::endl;
    std::cout << hue::white_on_green << "hue::white_on_green" << hue::reset << std::endl;
    std::cout << hue::white_on_aqua << "hue::white_on_aqua" << hue::reset << std::endl;
    std::cout << hue::white_on_cyan << "hue::white_on_cyan" << hue::reset << std::endl;
    std::cout << hue::white_on_red << "hue::white_on_red" << hue::reset << std::endl;
    std::cout << hue::white_on_purple << "hue::white_on_purple" << hue::reset << std::endl;
    std::cout << hue::white_on_magenta << "hue::white_on_magenta" << hue::reset << std::endl;
    std::cout << hue::white_on_yellow << "hue::white_on_yellow" << hue::reset << std::endl;
    std::cout << hue::white_on_white << "hue::white_on_white" << hue::reset << std::endl;
    std::cout << hue::white_on_gray << "hue::white_on_gray" << hue::reset << std::endl;
    std::cout << hue::white_on_light_blue << "hue::white_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::white_on_light_green << "hue::white_on_light_green" << hue::reset << std::endl;
    std::cout << hue::white_on_light_aqua << "hue::white_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::white_on_light_cyan << "hue::white_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::white_on_light_red << "hue::white_on_light_red" << hue::reset << std::endl;
    std::cout << hue::white_on_light_purple << "hue::white_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::white_on_light_magenta << "hue::white_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::white_on_light_yellow << "hue::white_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::white_on_bright_white << "hue::white_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::gray_on_black << "hue::gray_on_black" << hue::reset << std::endl;
    std::cout << hue::gray_on_blue << "hue::gray_on_blue" << hue::reset << std::endl;
    std::cout << hue::gray_on_green << "hue::gray_on_green" << hue::reset << std::endl;
    std::cout << hue::gray_on_aqua << "hue::gray_on_aqua" << hue::reset << std::endl;
    std::cout << hue::gray_on_cyan << "hue::gray_on_cyan" << hue::reset << std::endl;
    std::cout << hue::gray_on_red << "hue::gray_on_red" << hue::reset << std::endl;
    std::cout << hue::gray_on_purple << "hue::gray_on_purple" << hue::reset << std::endl;
    std::cout << hue::gray_on_magenta << "hue::gray_on_magenta" << hue::reset << std::endl;
    std::cout << hue::gray_on_yellow << "hue::gray_on_yellow" << hue::reset << std::endl;
    std::cout << hue::gray_on_white << "hue::gray_on_white" << hue::reset << std::endl;
    std::cout << hue::gray_on_gray << "hue::gray_on_gray" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_blue << "hue::gray_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_green << "hue::gray_on_light_green" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_aqua << "hue::gray_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_cyan << "hue::gray_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_red << "hue::gray_on_light_red" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_purple << "hue::gray_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_magenta << "hue::gray_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::gray_on_light_yellow << "hue::gray_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::gray_on_bright_white << "hue::gray_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_black << "hue::light_blue_on_black" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_blue << "hue::light_blue_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_green << "hue::light_blue_on_green" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_aqua << "hue::light_blue_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_cyan << "hue::light_blue_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_red << "hue::light_blue_on_red" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_purple << "hue::light_blue_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_magenta << "hue::light_blue_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_yellow << "hue::light_blue_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_white << "hue::light_blue_on_white" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_gray << "hue::light_blue_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_blue << "hue::light_blue_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_green << "hue::light_blue_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_aqua << "hue::light_blue_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_cyan << "hue::light_blue_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_red << "hue::light_blue_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_purple << "hue::light_blue_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_magenta << "hue::light_blue_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_light_yellow << "hue::light_blue_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_blue_on_bright_white << "hue::light_blue_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_green_on_black << "hue::light_green_on_black" << hue::reset << std::endl;
    std::cout << hue::light_green_on_blue << "hue::light_green_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_green_on_green << "hue::light_green_on_green" << hue::reset << std::endl;
    std::cout << hue::light_green_on_aqua << "hue::light_green_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_green_on_cyan << "hue::light_green_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_green_on_red << "hue::light_green_on_red" << hue::reset << std::endl;
    std::cout << hue::light_green_on_purple << "hue::light_green_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_green_on_magenta << "hue::light_green_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_green_on_yellow << "hue::light_green_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_green_on_white << "hue::light_green_on_white" << hue::reset << std::endl;
    std::cout << hue::light_green_on_gray << "hue::light_green_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_blue << "hue::light_green_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_green << "hue::light_green_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_aqua << "hue::light_green_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_cyan << "hue::light_green_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_red << "hue::light_green_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_purple << "hue::light_green_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_magenta << "hue::light_green_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_green_on_light_yellow << "hue::light_green_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_green_on_bright_white << "hue::light_green_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_black << "hue::light_aqua_on_black" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_blue << "hue::light_aqua_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_green << "hue::light_aqua_on_green" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_aqua << "hue::light_aqua_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_cyan << "hue::light_aqua_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_red << "hue::light_aqua_on_red" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_purple << "hue::light_aqua_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_magenta << "hue::light_aqua_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_yellow << "hue::light_aqua_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_white << "hue::light_aqua_on_white" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_gray << "hue::light_aqua_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_blue << "hue::light_aqua_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_green << "hue::light_aqua_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_aqua << "hue::light_aqua_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_cyan << "hue::light_aqua_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_red << "hue::light_aqua_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_purple << "hue::light_aqua_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_magenta << "hue::light_aqua_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_light_yellow << "hue::light_aqua_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_aqua_on_bright_white << "hue::light_aqua_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_black << "hue::light_cyan_on_black" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_blue << "hue::light_cyan_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_green << "hue::light_cyan_on_green" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_aqua << "hue::light_cyan_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_cyan << "hue::light_cyan_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_red << "hue::light_cyan_on_red" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_purple << "hue::light_cyan_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_magenta << "hue::light_cyan_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_yellow << "hue::light_cyan_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_white << "hue::light_cyan_on_white" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_gray << "hue::light_cyan_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_blue << "hue::light_cyan_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_green << "hue::light_cyan_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_aqua << "hue::light_cyan_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_cyan << "hue::light_cyan_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_red << "hue::light_cyan_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_purple << "hue::light_cyan_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_magenta << "hue::light_cyan_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_light_yellow << "hue::light_cyan_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_cyan_on_bright_white << "hue::light_cyan_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_red_on_black << "hue::light_red_on_black" << hue::reset << std::endl;
    std::cout << hue::light_red_on_blue << "hue::light_red_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_red_on_green << "hue::light_red_on_green" << hue::reset << std::endl;
    std::cout << hue::light_red_on_aqua << "hue::light_red_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_red_on_cyan << "hue::light_red_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_red_on_red << "hue::light_red_on_red" << hue::reset << std::endl;
    std::cout << hue::light_red_on_purple << "hue::light_red_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_red_on_magenta << "hue::light_red_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_red_on_yellow << "hue::light_red_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_red_on_white << "hue::light_red_on_white" << hue::reset << std::endl;
    std::cout << hue::light_red_on_gray << "hue::light_red_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_blue << "hue::light_red_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_green << "hue::light_red_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_aqua << "hue::light_red_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_cyan << "hue::light_red_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_red << "hue::light_red_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_purple << "hue::light_red_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_magenta << "hue::light_red_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_red_on_light_yellow << "hue::light_red_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_red_on_bright_white << "hue::light_red_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_black << "hue::light_purple_on_black" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_blue << "hue::light_purple_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_green << "hue::light_purple_on_green" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_aqua << "hue::light_purple_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_cyan << "hue::light_purple_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_red << "hue::light_purple_on_red" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_purple << "hue::light_purple_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_magenta << "hue::light_purple_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_yellow << "hue::light_purple_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_white << "hue::light_purple_on_white" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_gray << "hue::light_purple_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_blue << "hue::light_purple_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_green << "hue::light_purple_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_aqua << "hue::light_purple_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_cyan << "hue::light_purple_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_red << "hue::light_purple_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_purple << "hue::light_purple_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_magenta << "hue::light_purple_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_light_yellow << "hue::light_purple_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_purple_on_bright_white << "hue::light_purple_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_black << "hue::light_magenta_on_black" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_blue << "hue::light_magenta_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_green << "hue::light_magenta_on_green" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_aqua << "hue::light_magenta_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_cyan << "hue::light_magenta_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_red << "hue::light_magenta_on_red" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_purple << "hue::light_magenta_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_magenta << "hue::light_magenta_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_yellow << "hue::light_magenta_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_white << "hue::light_magenta_on_white" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_gray << "hue::light_magenta_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_blue << "hue::light_magenta_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_green << "hue::light_magenta_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_aqua << "hue::light_magenta_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_cyan << "hue::light_magenta_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_red << "hue::light_magenta_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_purple << "hue::light_magenta_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_magenta << "hue::light_magenta_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_light_yellow << "hue::light_magenta_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_magenta_on_bright_white << "hue::light_magenta_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_black << "hue::light_yellow_on_black" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_blue << "hue::light_yellow_on_blue" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_green << "hue::light_yellow_on_green" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_aqua << "hue::light_yellow_on_aqua" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_cyan << "hue::light_yellow_on_cyan" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_red << "hue::light_yellow_on_red" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_purple << "hue::light_yellow_on_purple" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_magenta << "hue::light_yellow_on_magenta" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_yellow << "hue::light_yellow_on_yellow" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_white << "hue::light_yellow_on_white" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_gray << "hue::light_yellow_on_gray" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_blue << "hue::light_yellow_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_green << "hue::light_yellow_on_light_green" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_aqua << "hue::light_yellow_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_cyan << "hue::light_yellow_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_red << "hue::light_yellow_on_light_red" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_purple << "hue::light_yellow_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_magenta << "hue::light_yellow_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_light_yellow << "hue::light_yellow_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::light_yellow_on_bright_white << "hue::light_yellow_on_bright_white" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_black << "hue::bright_white_on_black" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_blue << "hue::bright_white_on_blue" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_green << "hue::bright_white_on_green" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_aqua << "hue::bright_white_on_aqua" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_cyan << "hue::bright_white_on_cyan" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_red << "hue::bright_white_on_red" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_purple << "hue::bright_white_on_purple" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_magenta << "hue::bright_white_on_magenta" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_yellow << "hue::bright_white_on_yellow" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_white << "hue::bright_white_on_white" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_gray << "hue::bright_white_on_gray" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_blue << "hue::bright_white_on_light_blue" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_green << "hue::bright_white_on_light_green" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_aqua << "hue::bright_white_on_light_aqua" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_cyan << "hue::bright_white_on_light_cyan" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_red << "hue::bright_white_on_light_red" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_purple << "hue::bright_white_on_light_purple" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_magenta << "hue::bright_white_on_light_magenta" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_light_yellow << "hue::bright_white_on_light_yellow" << hue::reset << std::endl;
    std::cout << hue::bright_white_on_bright_white << "hue::bright_white_on_bright_white" << hue::reset << std::endl;
}

void exhaustive_dye_api_test()
{
    std::cout << dye::black("dye::black") << std::endl;
    std::cout << dye::blue("dye::blue") << std::endl;
    std::cout << dye::green("dye::green") << std::endl;
    std::cout << dye::aqua("dye::aqua") << std::endl;
    std::cout << dye::cyan("dye::cyan") << std::endl;
    std::cout << dye::red("dye::red") << std::endl;
    std::cout << dye::purple("dye::purple") << std::endl;
    std::cout << dye::magenta("dye::magenta") << std::endl;
    std::cout << dye::yellow("dye::yellow") << std::endl;
    std::cout << dye::white("dye::white") << std::endl;
    std::cout << dye::gray("dye::gray") << std::endl;
    std::cout << dye::light_blue("dye::light_blue") << std::endl;
    std::cout << dye::light_green("dye::light_green") << std::endl;
    std::cout << dye::light_aqua("dye::light_aqua") << std::endl;
    std::cout << dye::light_cyan("dye::light_cyan") << std::endl;
    std::cout << dye::light_red("dye::light_red") << std::endl;
    std::cout << dye::light_purple("dye::light_purple") << std::endl;
    std::cout << dye::light_magenta("dye::light_magenta") << std::endl;
    std::cout << dye::light_yellow("dye::light_yellow") << std::endl;
    std::cout << dye::bright_white("dye::bright_white") << std::endl;
    std::cout << dye::on_black("dye::on_black") << std::endl;
    std::cout << dye::on_blue("dye::on_blue") << std::endl;
    std::cout << dye::on_green("dye::on_green") << std::endl;
    std::cout << dye::on_aqua("dye::on_aqua") << std::endl;
    std::cout << dye::on_cyan("dye::on_cyan") << std::endl;
    std::cout << dye::on_red("dye::on_red") << std::endl;
    std::cout << dye::on_purple("dye::on_purple") << std::endl;
    std::cout << dye::on_magenta("dye::on_magenta") << std::endl;
    std::cout << dye::on_yellow("dye::on_yellow") << std::endl;
    std::cout << dye::on_white("dye::on_white") << std::endl;
    std::cout << dye::on_gray("dye::on_gray") << std::endl;
    std::cout << dye::on_light_blue("dye::on_light_blue") << std::endl;
    std::cout << dye::on_light_green("dye::on_light_green") << std::endl;
    std::cout << dye::on_light_aqua("dye::on_light_aqua") << std::endl;
    std::cout << dye::on_light_cyan("dye::on_light_cyan") << std::endl;
    std::cout << dye::on_light_red("dye::on_light_red") << std::endl;
    std::cout << dye::on_light_purple("dye::on_light_purple") << std::endl;
    std::cout << dye::on_light_magenta("dye::on_light_magenta") << std::endl;
    std::cout << dye::on_light_yellow("dye::on_light_yellow") << std::endl;
    std::cout << dye::on_bright_white("dye::on_bright_white") << std::endl;
    std::cout << dye::black_on_black("dye::black_on_black") << std::endl;
    std::cout << dye::black_on_blue("dye::black_on_blue") << std::endl;
    std::cout << dye::black_on_green("dye::black_on_green") << std::endl;
    std::cout << dye::black_on_aqua("dye::black_on_aqua") << std::endl;
    std::cout << dye::black_on_cyan("dye::black_on_cyan") << std::endl;
    std::cout << dye::black_on_red("dye::black_on_red") << std::endl;
    std::cout << dye::black_on_purple("dye::black_on_purple") << std::endl;
    std::cout << dye::black_on_magenta("dye::black_on_magenta") << std::endl;
    std::cout << dye::black_on_yellow("dye::black_on_yellow") << std::endl;
    std::cout << dye::black_on_white("dye::black_on_white") << std::endl;
    std::cout << dye::black_on_gray("dye::black_on_gray") << std::endl;
    std::cout << dye::black_on_light_blue("dye::black_on_light_blue") << std::endl;
    std::cout << dye::black_on_light_green("dye::black_on_light_green") << std::endl;
    std::cout << dye::black_on_light_aqua("dye::black_on_light_aqua") << std::endl;
    std::cout << dye::black_on_light_cyan("dye::black_on_light_cyan") << std::endl;
    std::cout << dye::black_on_light_red("dye::black_on_light_red") << std::endl;
    std::cout << dye::black_on_light_purple("dye::black_on_light_purple") << std::endl;
    std::cout << dye::black_on_light_magenta("dye::black_on_light_magenta") << std::endl;
    std::cout << dye::black_on_light_yellow("dye::black_on_light_yellow") << std::endl;
    std::cout << dye::black_on_bright_white("dye::black_on_bright_white") << std::endl;
    std::cout << dye::blue_on_black("dye::blue_on_black") << std::endl;
    std::cout << dye::blue_on_blue("dye::blue_on_blue") << std::endl;
    std::cout << dye::blue_on_green("dye::blue_on_green") << std::endl;
    std::cout << dye::blue_on_aqua("dye::blue_on_aqua") << std::endl;
    std::cout << dye::blue_on_cyan("dye::blue_on_cyan") << std::endl;
    std::cout << dye::blue_on_red("dye::blue_on_red") << std::endl;
    std::cout << dye::blue_on_purple("dye::blue_on_purple") << std::endl;
    std::cout << dye::blue_on_magenta("dye::blue_on_magenta") << std::endl;
    std::cout << dye::blue_on_yellow("dye::blue_on_yellow") << std::endl;
    std::cout << dye::blue_on_white("dye::blue_on_white") << std::endl;
    std::cout << dye::blue_on_gray("dye::blue_on_gray") << std::endl;
    std::cout << dye::blue_on_light_blue("dye::blue_on_light_blue") << std::endl;
    std::cout << dye::blue_on_light_green("dye::blue_on_light_green") << std::endl;
    std::cout << dye::blue_on_light_aqua("dye::blue_on_light_aqua") << std::endl;
    std::cout << dye::blue_on_light_cyan("dye::blue_on_light_cyan") << std::endl;
    std::cout << dye::blue_on_light_red("dye::blue_on_light_red") << std::endl;
    std::cout << dye::blue_on_light_purple("dye::blue_on_light_purple") << std::endl;
    std::cout << dye::blue_on_light_magenta("dye::blue_on_light_magenta") << std::endl;
    std::cout << dye::blue_on_light_yellow("dye::blue_on_light_yellow") << std::endl;
    std::cout << dye::blue_on_bright_white("dye::blue_on_bright_white") << std::endl;
    std::cout << dye::green_on_black("dye::green_on_black") << std::endl;
    std::cout << dye::green_on_blue("dye::green_on_blue") << std::endl;
    std::cout << dye::green_on_green("dye::green_on_green") << std::endl;
    std::cout << dye::green_on_aqua("dye::green_on_aqua") << std::endl;
    std::cout << dye::green_on_cyan("dye::green_on_cyan") << std::endl;
    std::cout << dye::green_on_red("dye::green_on_red") << std::endl;
    std::cout << dye::green_on_purple("dye::green_on_purple") << std::endl;
    std::cout << dye::green_on_magenta("dye::green_on_magenta") << std::endl;
    std::cout << dye::green_on_yellow("dye::green_on_yellow") << std::endl;
    std::cout << dye::green_on_white("dye::green_on_white") << std::endl;
    std::cout << dye::green_on_gray("dye::green_on_gray") << std::endl;
    std::cout << dye::green_on_light_blue("dye::green_on_light_blue") << std::endl;
    std::cout << dye::green_on_light_green("dye::green_on_light_green") << std::endl;
    std::cout << dye::green_on_light_aqua("dye::green_on_light_aqua") << std::endl;
    std::cout << dye::green_on_light_cyan("dye::green_on_light_cyan") << std::endl;
    std::cout << dye::green_on_light_red("dye::green_on_light_red") << std::endl;
    std::cout << dye::green_on_light_purple("dye::green_on_light_purple") << std::endl;
    std::cout << dye::green_on_light_magenta("dye::green_on_light_magenta") << std::endl;
    std::cout << dye::green_on_light_yellow("dye::green_on_light_yellow") << std::endl;
    std::cout << dye::green_on_bright_white("dye::green_on_bright_white") << std::endl;
    std::cout << dye::aqua_on_black("dye::aqua_on_black") << std::endl;
    std::cout << dye::aqua_on_blue("dye::aqua_on_blue") << std::endl;
    std::cout << dye::aqua_on_green("dye::aqua_on_green") << std::endl;
    std::cout << dye::aqua_on_aqua("dye::aqua_on_aqua") << std::endl;
    std::cout << dye::aqua_on_cyan("dye::aqua_on_cyan") << std::endl;
    std::cout << dye::aqua_on_red("dye::aqua_on_red") << std::endl;
    std::cout << dye::aqua_on_purple("dye::aqua_on_purple") << std::endl;
    std::cout << dye::aqua_on_magenta("dye::aqua_on_magenta") << std::endl;
    std::cout << dye::aqua_on_yellow("dye::aqua_on_yellow") << std::endl;
    std::cout << dye::aqua_on_white("dye::aqua_on_white") << std::endl;
    std::cout << dye::aqua_on_gray("dye::aqua_on_gray") << std::endl;
    std::cout << dye::aqua_on_light_blue("dye::aqua_on_light_blue") << std::endl;
    std::cout << dye::aqua_on_light_green("dye::aqua_on_light_green") << std::endl;
    std::cout << dye::aqua_on_light_aqua("dye::aqua_on_light_aqua") << std::endl;
    std::cout << dye::aqua_on_light_cyan("dye::aqua_on_light_cyan") << std::endl;
    std::cout << dye::aqua_on_light_red("dye::aqua_on_light_red") << std::endl;
    std::cout << dye::aqua_on_light_purple("dye::aqua_on_light_purple") << std::endl;
    std::cout << dye::aqua_on_light_magenta("dye::aqua_on_light_magenta") << std::endl;
    std::cout << dye::aqua_on_light_yellow("dye::aqua_on_light_yellow") << std::endl;
    std::cout << dye::aqua_on_bright_white("dye::aqua_on_bright_white") << std::endl;
    std::cout << dye::cyan_on_black("dye::cyan_on_black") << std::endl;
    std::cout << dye::cyan_on_blue("dye::cyan_on_blue") << std::endl;
    std::cout << dye::cyan_on_green("dye::cyan_on_green") << std::endl;
    std::cout << dye::cyan_on_aqua("dye::cyan_on_aqua") << std::endl;
    std::cout << dye::cyan_on_cyan("dye::cyan_on_cyan") << std::endl;
    std::cout << dye::cyan_on_red("dye::cyan_on_red") << std::endl;
    std::cout << dye::cyan_on_purple("dye::cyan_on_purple") << std::endl;
    std::cout << dye::cyan_on_magenta("dye::cyan_on_magenta") << std::endl;
    std::cout << dye::cyan_on_yellow("dye::cyan_on_yellow") << std::endl;
    std::cout << dye::cyan_on_white("dye::cyan_on_white") << std::endl;
    std::cout << dye::cyan_on_gray("dye::cyan_on_gray") << std::endl;
    std::cout << dye::cyan_on_light_blue("dye::cyan_on_light_blue") << std::endl;
    std::cout << dye::cyan_on_light_green("dye::cyan_on_light_green") << std::endl;
    std::cout << dye::cyan_on_light_aqua("dye::cyan_on_light_aqua") << std::endl;
    std::cout << dye::cyan_on_light_cyan("dye::cyan_on_light_cyan") << std::endl;
    std::cout << dye::cyan_on_light_red("dye::cyan_on_light_red") << std::endl;
    std::cout << dye::cyan_on_light_purple("dye::cyan_on_light_purple") << std::endl;
    std::cout << dye::cyan_on_light_magenta("dye::cyan_on_light_magenta") << std::endl;
    std::cout << dye::cyan_on_light_yellow("dye::cyan_on_light_yellow") << std::endl;
    std::cout << dye::cyan_on_bright_white("dye::cyan_on_bright_white") << std::endl;
    std::cout << dye::red_on_black("dye::red_on_black") << std::endl;
    std::cout << dye::red_on_blue("dye::red_on_blue") << std::endl;
    std::cout << dye::red_on_green("dye::red_on_green") << std::endl;
    std::cout << dye::red_on_aqua("dye::red_on_aqua") << std::endl;
    std::cout << dye::red_on_cyan("dye::red_on_cyan") << std::endl;
    std::cout << dye::red_on_red("dye::red_on_red") << std::endl;
    std::cout << dye::red_on_purple("dye::red_on_purple") << std::endl;
    std::cout << dye::red_on_magenta("dye::red_on_magenta") << std::endl;
    std::cout << dye::red_on_yellow("dye::red_on_yellow") << std::endl;
    std::cout << dye::red_on_white("dye::red_on_white") << std::endl;
    std::cout << dye::red_on_gray("dye::red_on_gray") << std::endl;
    std::cout << dye::red_on_light_blue("dye::red_on_light_blue") << std::endl;
    std::cout << dye::red_on_light_green("dye::red_on_light_green") << std::endl;
    std::cout << dye::red_on_light_aqua("dye::red_on_light_aqua") << std::endl;
    std::cout << dye::red_on_light_cyan("dye::red_on_light_cyan") << std::endl;
    std::cout << dye::red_on_light_red("dye::red_on_light_red") << std::endl;
    std::cout << dye::red_on_light_purple("dye::red_on_light_purple") << std::endl;
    std::cout << dye::red_on_light_magenta("dye::red_on_light_magenta") << std::endl;
    std::cout << dye::red_on_light_yellow("dye::red_on_light_yellow") << std::endl;
    std::cout << dye::red_on_bright_white("dye::red_on_bright_white") << std::endl;
    std::cout << dye::purple_on_black("dye::purple_on_black") << std::endl;
    std::cout << dye::purple_on_blue("dye::purple_on_blue") << std::endl;
    std::cout << dye::purple_on_green("dye::purple_on_green") << std::endl;
    std::cout << dye::purple_on_aqua("dye::purple_on_aqua") << std::endl;
    std::cout << dye::purple_on_cyan("dye::purple_on_cyan") << std::endl;
    std::cout << dye::purple_on_red("dye::purple_on_red") << std::endl;
    std::cout << dye::purple_on_purple("dye::purple_on_purple") << std::endl;
    std::cout << dye::purple_on_magenta("dye::purple_on_magenta") << std::endl;
    std::cout << dye::purple_on_yellow("dye::purple_on_yellow") << std::endl;
    std::cout << dye::purple_on_white("dye::purple_on_white") << std::endl;
    std::cout << dye::purple_on_gray("dye::purple_on_gray") << std::endl;
    std::cout << dye::purple_on_light_blue("dye::purple_on_light_blue") << std::endl;
    std::cout << dye::purple_on_light_green("dye::purple_on_light_green") << std::endl;
    std::cout << dye::purple_on_light_aqua("dye::purple_on_light_aqua") << std::endl;
    std::cout << dye::purple_on_light_cyan("dye::purple_on_light_cyan") << std::endl;
    std::cout << dye::purple_on_light_red("dye::purple_on_light_red") << std::endl;
    std::cout << dye::purple_on_light_purple("dye::purple_on_light_purple") << std::endl;
    std::cout << dye::purple_on_light_magenta("dye::purple_on_light_magenta") << std::endl;
    std::cout << dye::purple_on_light_yellow("dye::purple_on_light_yellow") << std::endl;
    std::cout << dye::purple_on_bright_white("dye::purple_on_bright_white") << std::endl;
    std::cout << dye::magenta_on_black("dye::magenta_on_black") << std::endl;
    std::cout << dye::magenta_on_blue("dye::magenta_on_blue") << std::endl;
    std::cout << dye::magenta_on_green("dye::magenta_on_green") << std::endl;
    std::cout << dye::magenta_on_aqua("dye::magenta_on_aqua") << std::endl;
    std::cout << dye::magenta_on_cyan("dye::magenta_on_cyan") << std::endl;
    std::cout << dye::magenta_on_red("dye::magenta_on_red") << std::endl;
    std::cout << dye::magenta_on_purple("dye::magenta_on_purple") << std::endl;
    std::cout << dye::magenta_on_magenta("dye::magenta_on_magenta") << std::endl;
    std::cout << dye::magenta_on_yellow("dye::magenta_on_yellow") << std::endl;
    std::cout << dye::magenta_on_white("dye::magenta_on_white") << std::endl;
    std::cout << dye::magenta_on_gray("dye::magenta_on_gray") << std::endl;
    std::cout << dye::magenta_on_light_blue("dye::magenta_on_light_blue") << std::endl;
    std::cout << dye::magenta_on_light_green("dye::magenta_on_light_green") << std::endl;
    std::cout << dye::magenta_on_light_aqua("dye::magenta_on_light_aqua") << std::endl;
    std::cout << dye::magenta_on_light_cyan("dye::magenta_on_light_cyan") << std::endl;
    std::cout << dye::magenta_on_light_red("dye::magenta_on_light_red") << std::endl;
    std::cout << dye::magenta_on_light_purple("dye::magenta_on_light_purple") << std::endl;
    std::cout << dye::magenta_on_light_magenta("dye::magenta_on_light_magenta") << std::endl;
    std::cout << dye::magenta_on_light_yellow("dye::magenta_on_light_yellow") << std::endl;
    std::cout << dye::magenta_on_bright_white("dye::magenta_on_bright_white") << std::endl;
    std::cout << dye::yellow_on_black("dye::yellow_on_black") << std::endl;
    std::cout << dye::yellow_on_blue("dye::yellow_on_blue") << std::endl;
    std::cout << dye::yellow_on_green("dye::yellow_on_green") << std::endl;
    std::cout << dye::yellow_on_aqua("dye::yellow_on_aqua") << std::endl;
    std::cout << dye::yellow_on_cyan("dye::yellow_on_cyan") << std::endl;
    std::cout << dye::yellow_on_red("dye::yellow_on_red") << std::endl;
    std::cout << dye::yellow_on_purple("dye::yellow_on_purple") << std::endl;
    std::cout << dye::yellow_on_magenta("dye::yellow_on_magenta") << std::endl;
    std::cout << dye::yellow_on_yellow("dye::yellow_on_yellow") << std::endl;
    std::cout << dye::yellow_on_white("dye::yellow_on_white") << std::endl;
    std::cout << dye::yellow_on_gray("dye::yellow_on_gray") << std::endl;
    std::cout << dye::yellow_on_light_blue("dye::yellow_on_light_blue") << std::endl;
    std::cout << dye::yellow_on_light_green("dye::yellow_on_light_green") << std::endl;
    std::cout << dye::yellow_on_light_aqua("dye::yellow_on_light_aqua") << std::endl;
    std::cout << dye::yellow_on_light_cyan("dye::yellow_on_light_cyan") << std::endl;
    std::cout << dye::yellow_on_light_red("dye::yellow_on_light_red") << std::endl;
    std::cout << dye::yellow_on_light_purple("dye::yellow_on_light_purple") << std::endl;
    std::cout << dye::yellow_on_light_magenta("dye::yellow_on_light_magenta") << std::endl;
    std::cout << dye::yellow_on_light_yellow("dye::yellow_on_light_yellow") << std::endl;
    std::cout << dye::yellow_on_bright_white("dye::yellow_on_bright_white") << std::endl;
    std::cout << dye::white_on_black("dye::white_on_black") << std::endl;
    std::cout << dye::white_on_blue("dye::white_on_blue") << std::endl;
    std::cout << dye::white_on_green("dye::white_on_green") << std::endl;
    std::cout << dye::white_on_aqua("dye::white_on_aqua") << std::endl;
    std::cout << dye::white_on_cyan("dye::white_on_cyan") << std::endl;
    std::cout << dye::white_on_red("dye::white_on_red") << std::endl;
    std::cout << dye::white_on_purple("dye::white_on_purple") << std::endl;
    std::cout << dye::white_on_magenta("dye::white_on_magenta") << std::endl;
    std::cout << dye::white_on_yellow("dye::white_on_yellow") << std::endl;
    std::cout << dye::white_on_white("dye::white_on_white") << std::endl;
    std::cout << dye::white_on_gray("dye::white_on_gray") << std::endl;
    std::cout << dye::white_on_light_blue("dye::white_on_light_blue") << std::endl;
    std::cout << dye::white_on_light_green("dye::white_on_light_green") << std::endl;
    std::cout << dye::white_on_light_aqua("dye::white_on_light_aqua") << std::endl;
    std::cout << dye::white_on_light_cyan("dye::white_on_light_cyan") << std::endl;
    std::cout << dye::white_on_light_red("dye::white_on_light_red") << std::endl;
    std::cout << dye::white_on_light_purple("dye::white_on_light_purple") << std::endl;
    std::cout << dye::white_on_light_magenta("dye::white_on_light_magenta") << std::endl;
    std::cout << dye::white_on_light_yellow("dye::white_on_light_yellow") << std::endl;
    std::cout << dye::white_on_bright_white("dye::white_on_bright_white") << std::endl;
    std::cout << dye::gray_on_black("dye::gray_on_black") << std::endl;
    std::cout << dye::gray_on_blue("dye::gray_on_blue") << std::endl;
    std::cout << dye::gray_on_green("dye::gray_on_green") << std::endl;
    std::cout << dye::gray_on_aqua("dye::gray_on_aqua") << std::endl;
    std::cout << dye::gray_on_cyan("dye::gray_on_cyan") << std::endl;
    std::cout << dye::gray_on_red("dye::gray_on_red") << std::endl;
    std::cout << dye::gray_on_purple("dye::gray_on_purple") << std::endl;
    std::cout << dye::gray_on_magenta("dye::gray_on_magenta") << std::endl;
    std::cout << dye::gray_on_yellow("dye::gray_on_yellow") << std::endl;
    std::cout << dye::gray_on_white("dye::gray_on_white") << std::endl;
    std::cout << dye::gray_on_gray("dye::gray_on_gray") << std::endl;
    std::cout << dye::gray_on_light_blue("dye::gray_on_light_blue") << std::endl;
    std::cout << dye::gray_on_light_green("dye::gray_on_light_green") << std::endl;
    std::cout << dye::gray_on_light_aqua("dye::gray_on_light_aqua") << std::endl;
    std::cout << dye::gray_on_light_cyan("dye::gray_on_light_cyan") << std::endl;
    std::cout << dye::gray_on_light_red("dye::gray_on_light_red") << std::endl;
    std::cout << dye::gray_on_light_purple("dye::gray_on_light_purple") << std::endl;
    std::cout << dye::gray_on_light_magenta("dye::gray_on_light_magenta") << std::endl;
    std::cout << dye::gray_on_light_yellow("dye::gray_on_light_yellow") << std::endl;
    std::cout << dye::gray_on_bright_white("dye::gray_on_bright_white") << std::endl;
    std::cout << dye::light_blue_on_black("dye::light_blue_on_black") << std::endl;
    std::cout << dye::light_blue_on_blue("dye::light_blue_on_blue") << std::endl;
    std::cout << dye::light_blue_on_green("dye::light_blue_on_green") << std::endl;
    std::cout << dye::light_blue_on_aqua("dye::light_blue_on_aqua") << std::endl;
    std::cout << dye::light_blue_on_cyan("dye::light_blue_on_cyan") << std::endl;
    std::cout << dye::light_blue_on_red("dye::light_blue_on_red") << std::endl;
    std::cout << dye::light_blue_on_purple("dye::light_blue_on_purple") << std::endl;
    std::cout << dye::light_blue_on_magenta("dye::light_blue_on_magenta") << std::endl;
    std::cout << dye::light_blue_on_yellow("dye::light_blue_on_yellow") << std::endl;
    std::cout << dye::light_blue_on_white("dye::light_blue_on_white") << std::endl;
    std::cout << dye::light_blue_on_gray("dye::light_blue_on_gray") << std::endl;
    std::cout << dye::light_blue_on_light_blue("dye::light_blue_on_light_blue") << std::endl;
    std::cout << dye::light_blue_on_light_green("dye::light_blue_on_light_green") << std::endl;
    std::cout << dye::light_blue_on_light_aqua("dye::light_blue_on_light_aqua") << std::endl;
    std::cout << dye::light_blue_on_light_cyan("dye::light_blue_on_light_cyan") << std::endl;
    std::cout << dye::light_blue_on_light_red("dye::light_blue_on_light_red") << std::endl;
    std::cout << dye::light_blue_on_light_purple("dye::light_blue_on_light_purple") << std::endl;
    std::cout << dye::light_blue_on_light_magenta("dye::light_blue_on_light_magenta") << std::endl;
    std::cout << dye::light_blue_on_light_yellow("dye::light_blue_on_light_yellow") << std::endl;
    std::cout << dye::light_blue_on_bright_white("dye::light_blue_on_bright_white") << std::endl;
    std::cout << dye::light_green_on_black("dye::light_green_on_black") << std::endl;
    std::cout << dye::light_green_on_blue("dye::light_green_on_blue") << std::endl;
    std::cout << dye::light_green_on_green("dye::light_green_on_green") << std::endl;
    std::cout << dye::light_green_on_aqua("dye::light_green_on_aqua") << std::endl;
    std::cout << dye::light_green_on_cyan("dye::light_green_on_cyan") << std::endl;
    std::cout << dye::light_green_on_red("dye::light_green_on_red") << std::endl;
    std::cout << dye::light_green_on_purple("dye::light_green_on_purple") << std::endl;
    std::cout << dye::light_green_on_magenta("dye::light_green_on_magenta") << std::endl;
    std::cout << dye::light_green_on_yellow("dye::light_green_on_yellow") << std::endl;
    std::cout << dye::light_green_on_white("dye::light_green_on_white") << std::endl;
    std::cout << dye::light_green_on_gray("dye::light_green_on_gray") << std::endl;
    std::cout << dye::light_green_on_light_blue("dye::light_green_on_light_blue") << std::endl;
    std::cout << dye::light_green_on_light_green("dye::light_green_on_light_green") << std::endl;
    std::cout << dye::light_green_on_light_aqua("dye::light_green_on_light_aqua") << std::endl;
    std::cout << dye::light_green_on_light_cyan("dye::light_green_on_light_cyan") << std::endl;
    std::cout << dye::light_green_on_light_red("dye::light_green_on_light_red") << std::endl;
    std::cout << dye::light_green_on_light_purple("dye::light_green_on_light_purple") << std::endl;
    std::cout << dye::light_green_on_light_magenta("dye::light_green_on_light_magenta") << std::endl;
    std::cout << dye::light_green_on_light_yellow("dye::light_green_on_light_yellow") << std::endl;
    std::cout << dye::light_green_on_bright_white("dye::light_green_on_bright_white") << std::endl;
    std::cout << dye::light_aqua_on_black("dye::light_aqua_on_black") << std::endl;
    std::cout << dye::light_aqua_on_blue("dye::light_aqua_on_blue") << std::endl;
    std::cout << dye::light_aqua_on_green("dye::light_aqua_on_green") << std::endl;
    std::cout << dye::light_aqua_on_aqua("dye::light_aqua_on_aqua") << std::endl;
    std::cout << dye::light_aqua_on_cyan("dye::light_aqua_on_cyan") << std::endl;
    std::cout << dye::light_aqua_on_red("dye::light_aqua_on_red") << std::endl;
    std::cout << dye::light_aqua_on_purple("dye::light_aqua_on_purple") << std::endl;
    std::cout << dye::light_aqua_on_magenta("dye::light_aqua_on_magenta") << std::endl;
    std::cout << dye::light_aqua_on_yellow("dye::light_aqua_on_yellow") << std::endl;
    std::cout << dye::light_aqua_on_white("dye::light_aqua_on_white") << std::endl;
    std::cout << dye::light_aqua_on_gray("dye::light_aqua_on_gray") << std::endl;
    std::cout << dye::light_aqua_on_light_blue("dye::light_aqua_on_light_blue") << std::endl;
    std::cout << dye::light_aqua_on_light_green("dye::light_aqua_on_light_green") << std::endl;
    std::cout << dye::light_aqua_on_light_aqua("dye::light_aqua_on_light_aqua") << std::endl;
    std::cout << dye::light_aqua_on_light_cyan("dye::light_aqua_on_light_cyan") << std::endl;
    std::cout << dye::light_aqua_on_light_red("dye::light_aqua_on_light_red") << std::endl;
    std::cout << dye::light_aqua_on_light_purple("dye::light_aqua_on_light_purple") << std::endl;
    std::cout << dye::light_aqua_on_light_magenta("dye::light_aqua_on_light_magenta") << std::endl;
    std::cout << dye::light_aqua_on_light_yellow("dye::light_aqua_on_light_yellow") << std::endl;
    std::cout << dye::light_aqua_on_bright_white("dye::light_aqua_on_bright_white") << std::endl;
    std::cout << dye::light_cyan_on_black("dye::light_cyan_on_black") << std::endl;
    std::cout << dye::light_cyan_on_blue("dye::light_cyan_on_blue") << std::endl;
    std::cout << dye::light_cyan_on_green("dye::light_cyan_on_green") << std::endl;
    std::cout << dye::light_cyan_on_aqua("dye::light_cyan_on_aqua") << std::endl;
    std::cout << dye::light_cyan_on_cyan("dye::light_cyan_on_cyan") << std::endl;
    std::cout << dye::light_cyan_on_red("dye::light_cyan_on_red") << std::endl;
    std::cout << dye::light_cyan_on_purple("dye::light_cyan_on_purple") << std::endl;
    std::cout << dye::light_cyan_on_magenta("dye::light_cyan_on_magenta") << std::endl;
    std::cout << dye::light_cyan_on_yellow("dye::light_cyan_on_yellow") << std::endl;
    std::cout << dye::light_cyan_on_white("dye::light_cyan_on_white") << std::endl;
    std::cout << dye::light_cyan_on_gray("dye::light_cyan_on_gray") << std::endl;
    std::cout << dye::light_cyan_on_light_blue("dye::light_cyan_on_light_blue") << std::endl;
    std::cout << dye::light_cyan_on_light_green("dye::light_cyan_on_light_green") << std::endl;
    std::cout << dye::light_cyan_on_light_aqua("dye::light_cyan_on_light_aqua") << std::endl;
    std::cout << dye::light_cyan_on_light_cyan("dye::light_cyan_on_light_cyan") << std::endl;
    std::cout << dye::light_cyan_on_light_red("dye::light_cyan_on_light_red") << std::endl;
    std::cout << dye::light_cyan_on_light_purple("dye::light_cyan_on_light_purple") << std::endl;
    std::cout << dye::light_cyan_on_light_magenta("dye::light_cyan_on_light_magenta") << std::endl;
    std::cout << dye::light_cyan_on_light_yellow("dye::light_cyan_on_light_yellow") << std::endl;
    std::cout << dye::light_cyan_on_bright_white("dye::light_cyan_on_bright_white") << std::endl;
    std::cout << dye::light_red_on_black("dye::light_red_on_black") << std::endl;
    std::cout << dye::light_red_on_blue("dye::light_red_on_blue") << std::endl;
    std::cout << dye::light_red_on_green("dye::light_red_on_green") << std::endl;
    std::cout << dye::light_red_on_aqua("dye::light_red_on_aqua") << std::endl;
    std::cout << dye::light_red_on_cyan("dye::light_red_on_cyan") << std::endl;
    std::cout << dye::light_red_on_red("dye::light_red_on_red") << std::endl;
    std::cout << dye::light_red_on_purple("dye::light_red_on_purple") << std::endl;
    std::cout << dye::light_red_on_magenta("dye::light_red_on_magenta") << std::endl;
    std::cout << dye::light_red_on_yellow("dye::light_red_on_yellow") << std::endl;
    std::cout << dye::light_red_on_white("dye::light_red_on_white") << std::endl;
    std::cout << dye::light_red_on_gray("dye::light_red_on_gray") << std::endl;
    std::cout << dye::light_red_on_light_blue("dye::light_red_on_light_blue") << std::endl;
    std::cout << dye::light_red_on_light_green("dye::light_red_on_light_green") << std::endl;
    std::cout << dye::light_red_on_light_aqua("dye::light_red_on_light_aqua") << std::endl;
    std::cout << dye::light_red_on_light_cyan("dye::light_red_on_light_cyan") << std::endl;
    std::cout << dye::light_red_on_light_red("dye::light_red_on_light_red") << std::endl;
    std::cout << dye::light_red_on_light_purple("dye::light_red_on_light_purple") << std::endl;
    std::cout << dye::light_red_on_light_magenta("dye::light_red_on_light_magenta") << std::endl;
    std::cout << dye::light_red_on_light_yellow("dye::light_red_on_light_yellow") << std::endl;
    std::cout << dye::light_red_on_bright_white("dye::light_red_on_bright_white") << std::endl;
    std::cout << dye::light_purple_on_black("dye::light_purple_on_black") << std::endl;
    std::cout << dye::light_purple_on_blue("dye::light_purple_on_blue") << std::endl;
    std::cout << dye::light_purple_on_green("dye::light_purple_on_green") << std::endl;
    std::cout << dye::light_purple_on_aqua("dye::light_purple_on_aqua") << std::endl;
    std::cout << dye::light_purple_on_cyan("dye::light_purple_on_cyan") << std::endl;
    std::cout << dye::light_purple_on_red("dye::light_purple_on_red") << std::endl;
    std::cout << dye::light_purple_on_purple("dye::light_purple_on_purple") << std::endl;
    std::cout << dye::light_purple_on_magenta("dye::light_purple_on_magenta") << std::endl;
    std::cout << dye::light_purple_on_yellow("dye::light_purple_on_yellow") << std::endl;
    std::cout << dye::light_purple_on_white("dye::light_purple_on_white") << std::endl;
    std::cout << dye::light_purple_on_gray("dye::light_purple_on_gray") << std::endl;
    std::cout << dye::light_purple_on_light_blue("dye::light_purple_on_light_blue") << std::endl;
    std::cout << dye::light_purple_on_light_green("dye::light_purple_on_light_green") << std::endl;
    std::cout << dye::light_purple_on_light_aqua("dye::light_purple_on_light_aqua") << std::endl;
    std::cout << dye::light_purple_on_light_cyan("dye::light_purple_on_light_cyan") << std::endl;
    std::cout << dye::light_purple_on_light_red("dye::light_purple_on_light_red") << std::endl;
    std::cout << dye::light_purple_on_light_purple("dye::light_purple_on_light_purple") << std::endl;
    std::cout << dye::light_purple_on_light_magenta("dye::light_purple_on_light_magenta") << std::endl;
    std::cout << dye::light_purple_on_light_yellow("dye::light_purple_on_light_yellow") << std::endl;
    std::cout << dye::light_purple_on_bright_white("dye::light_purple_on_bright_white") << std::endl;
    std::cout << dye::light_magenta_on_black("dye::light_magenta_on_black") << std::endl;
    std::cout << dye::light_magenta_on_blue("dye::light_magenta_on_blue") << std::endl;
    std::cout << dye::light_magenta_on_green("dye::light_magenta_on_green") << std::endl;
    std::cout << dye::light_magenta_on_aqua("dye::light_magenta_on_aqua") << std::endl;
    std::cout << dye::light_magenta_on_cyan("dye::light_magenta_on_cyan") << std::endl;
    std::cout << dye::light_magenta_on_red("dye::light_magenta_on_red") << std::endl;
    std::cout << dye::light_magenta_on_purple("dye::light_magenta_on_purple") << std::endl;
    std::cout << dye::light_magenta_on_magenta("dye::light_magenta_on_magenta") << std::endl;
    std::cout << dye::light_magenta_on_yellow("dye::light_magenta_on_yellow") << std::endl;
    std::cout << dye::light_magenta_on_white("dye::light_magenta_on_white") << std::endl;
    std::cout << dye::light_magenta_on_gray("dye::light_magenta_on_gray") << std::endl;
    std::cout << dye::light_magenta_on_light_blue("dye::light_magenta_on_light_blue") << std::endl;
    std::cout << dye::light_magenta_on_light_green("dye::light_magenta_on_light_green") << std::endl;
    std::cout << dye::light_magenta_on_light_aqua("dye::light_magenta_on_light_aqua") << std::endl;
    std::cout << dye::light_magenta_on_light_cyan("dye::light_magenta_on_light_cyan") << std::endl;
    std::cout << dye::light_magenta_on_light_red("dye::light_magenta_on_light_red") << std::endl;
    std::cout << dye::light_magenta_on_light_purple("dye::light_magenta_on_light_purple") << std::endl;
    std::cout << dye::light_magenta_on_light_magenta("dye::light_magenta_on_light_magenta") << std::endl;
    std::cout << dye::light_magenta_on_light_yellow("dye::light_magenta_on_light_yellow") << std::endl;
    std::cout << dye::light_magenta_on_bright_white("dye::light_magenta_on_bright_white") << std::endl;
    std::cout << dye::light_yellow_on_black("dye::light_yellow_on_black") << std::endl;
    std::cout << dye::light_yellow_on_blue("dye::light_yellow_on_blue") << std::endl;
    std::cout << dye::light_yellow_on_green("dye::light_yellow_on_green") << std::endl;
    std::cout << dye::light_yellow_on_aqua("dye::light_yellow_on_aqua") << std::endl;
    std::cout << dye::light_yellow_on_cyan("dye::light_yellow_on_cyan") << std::endl;
    std::cout << dye::light_yellow_on_red("dye::light_yellow_on_red") << std::endl;
    std::cout << dye::light_yellow_on_purple("dye::light_yellow_on_purple") << std::endl;
    std::cout << dye::light_yellow_on_magenta("dye::light_yellow_on_magenta") << std::endl;
    std::cout << dye::light_yellow_on_yellow("dye::light_yellow_on_yellow") << std::endl;
    std::cout << dye::light_yellow_on_white("dye::light_yellow_on_white") << std::endl;
    std::cout << dye::light_yellow_on_gray("dye::light_yellow_on_gray") << std::endl;
    std::cout << dye::light_yellow_on_light_blue("dye::light_yellow_on_light_blue") << std::endl;
    std::cout << dye::light_yellow_on_light_green("dye::light_yellow_on_light_green") << std::endl;
    std::cout << dye::light_yellow_on_light_aqua("dye::light_yellow_on_light_aqua") << std::endl;
    std::cout << dye::light_yellow_on_light_cyan("dye::light_yellow_on_light_cyan") << std::endl;
    std::cout << dye::light_yellow_on_light_red("dye::light_yellow_on_light_red") << std::endl;
    std::cout << dye::light_yellow_on_light_purple("dye::light_yellow_on_light_purple") << std::endl;
    std::cout << dye::light_yellow_on_light_magenta("dye::light_yellow_on_light_magenta") << std::endl;
    std::cout << dye::light_yellow_on_light_yellow("dye::light_yellow_on_light_yellow") << std::endl;
    std::cout << dye::light_yellow_on_bright_white("dye::light_yellow_on_bright_white") << std::endl;
    std::cout << dye::bright_white_on_black("dye::bright_white_on_black") << std::endl;
    std::cout << dye::bright_white_on_blue("dye::bright_white_on_blue") << std::endl;
    std::cout << dye::bright_white_on_green("dye::bright_white_on_green") << std::endl;
    std::cout << dye::bright_white_on_aqua("dye::bright_white_on_aqua") << std::endl;
    std::cout << dye::bright_white_on_cyan("dye::bright_white_on_cyan") << std::endl;
    std::cout << dye::bright_white_on_red("dye::bright_white_on_red") << std::endl;
    std::cout << dye::bright_white_on_purple("dye::bright_white_on_purple") << std::endl;
    std::cout << dye::bright_white_on_magenta("dye::bright_white_on_magenta") << std::endl;
    std::cout << dye::bright_white_on_yellow("dye::bright_white_on_yellow") << std::endl;
    std::cout << dye::bright_white_on_white("dye::bright_white_on_white") << std::endl;
    std::cout << dye::bright_white_on_gray("dye::bright_white_on_gray") << std::endl;
    std::cout << dye::bright_white_on_light_blue("dye::bright_white_on_light_blue") << std::endl;
    std::cout << dye::bright_white_on_light_green("dye::bright_white_on_light_green") << std::endl;
    std::cout << dye::bright_white_on_light_aqua("dye::bright_white_on_light_aqua") << std::endl;
    std::cout << dye::bright_white_on_light_cyan("dye::bright_white_on_light_cyan") << std::endl;
    std::cout << dye::bright_white_on_light_red("dye::bright_white_on_light_red") << std::endl;
    std::cout << dye::bright_white_on_light_purple("dye::bright_white_on_light_purple") << std::endl;
    std::cout << dye::bright_white_on_light_magenta("dye::bright_white_on_light_magenta") << std::endl;
    std::cout << dye::bright_white_on_light_yellow("dye::bright_white_on_light_yellow") << std::endl;
    std::cout << dye::bright_white_on_bright_white("dye::bright_white_on_bright_white") << std::endl;
}

int main()
{
    exhaustive_hue_api_test();
    exhaustive_dye_api_test();
    return 0;
}
